input: terminal
output: terminal
core:
  module: llama-cpp
  model_path: models/gemma-4-26B-A4B-it-UD-Q4_K_M.gguf
  n_gpu_layers: 5
  n_ctx: 32768
memory_short: flashback
memory_long:
  module: mem0
  model_path: models/gemma-4-E2B-it-Q4_K_M.gguf